name: hello-world

on : push
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@4
      - run : echo "$(cat hellow_world.txt)"  
